### ISSUE TITLE
Error from console

### ISSUE THREAD

**Issue by ghost** [GuizhanCraft/SoulJars-CN#3]
## Description (Required)

开启服务器，报错，但是能加载

## Steps to reproduce the Issue (Required)

1. 下载SoulJars汉化最新
2. 加载报错

## Expected behavior (Required)

正常加载

## Server Log / Error Report

```java
[19:12:59 ERROR]: [SoulJars] Item "EVOKER_SOUL_JAR" from SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d) has caused an Error!
[19:12:59 ERROR]: [SoulJars] You can report it here: https://github.com/ybw0014/SoulJars-CN/issues
[19:12:59 ERROR]: [SoulJars] Registering UnplaceableBlock - 'EVOKER_SOUL_JAR' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: UnplaceableBlock - 'EVOKER_SOUL_JAR' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d)) and UnplaceableBlock - 'EVOKER_SOUL_JAR' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d))
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:598) ~[Slimefun-v73ad1d2-canary.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:427) ~[Slimefun-v73ad1d2-canary.jar:?]
        at io.github.thebusybiscuit.souljars.SoulJars.registerSoul(SoulJars.java:86) ~[SoulJars-Build 7 zh-CN(ybw0014) (git 440734d).jar:?]
        at io.github.thebusybiscuit.souljars.SoulJars.onEnable(SoulJars.java:61) ~[SoulJars-Build 7 zh-CN(ybw0014) (git 440734d).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[purpur-1.19.jar:git-Purpur-1668]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:12:59 ERROR]: [SoulJars] Item "FILLED_EVOKER_SOUL_JAR" from SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d) has caused an Error!
[19:12:59 ERROR]: [SoulJars] You can report it here: https://github.com/ybw0014/SoulJars-CN/issues
[19:12:59 ERROR]: [SoulJars] Registering FilledJar - 'FILLED_EVOKER_SOUL_JAR' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: FilledJar - 'FILLED_EVOKER_SOUL_JAR' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d)) and FilledJar - 'FILLED_EVOKER_SOUL_JAR' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d))
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:598) ~[Slimefun-v73ad1d2-canary.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:427) ~[Slimefun-v73ad1d2-canary.jar:?]
        at io.github.thebusybiscuit.souljars.SoulJars.registerSoul(SoulJars.java:91) ~[SoulJars-Build 7 zh-CN(ybw0014) (git 440734d).jar:?]
        at io.github.thebusybiscuit.souljars.SoulJars.onEnable(SoulJars.java:61) ~[SoulJars-Build 7 zh-CN(ybw0014) (git 440734d).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[purpur-1.19.jar:git-Purpur-1668]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:12:59 ERROR]: [SoulJars] Item "EVOKER_BROKEN_SPAWNER" from SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d) has caused an Error!
[19:12:59 ERROR]: [SoulJars] You can report it here: https://github.com/ybw0014/SoulJars-CN/issues
[19:12:59 ERROR]: [SoulJars] Registering SlimefunItem - 'EVOKER_BROKEN_SPAWNER' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d)) has failed!
io.github.thebusybiscuit.slimefun4.api.exceptions.IdConflictException: Two items have conflicting ids: SlimefunItem - 'EVOKER_BROKEN_SPAWNER' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d)) and SlimefunItem - 'EVOKER_BROKEN_SPAWNER' (SoulJars vBuild 7 zh-CN(ybw0014) (git 440734d))
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.checkForConflicts(SlimefunItem.java:598) ~[Slimefun-v73ad1d2-canary.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.register(SlimefunItem.java:427) ~[Slimefun-v73ad1d2-canary.jar:?]
        at io.github.thebusybiscuit.souljars.SoulJars.registerSoul(SoulJars.java:98) ~[SoulJars-Build 7 zh-CN(ybw0014) (git 440734d).jar:?]
        at io.github.thebusybiscuit.souljars.SoulJars.onEnable(SoulJars.java:61) ~[SoulJars-Build 7 zh-CN(ybw0014) (git 440734d).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[purpur-1.19.jar:git-Purpur-1668]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1668]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1668]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:12:59 ERROR]: [SoulJars] IllegalArgumentException: 无效的生物类型: PIG_ZOMBIE
```

## Environment (Required)

 - Minecraft Version: 1.19 Purpur
 - CS-CoreLib Version: /
 - Slimefun Version: Slimefun 版本：汉化版 [73ad1d2](https://github.com/StarWishsama/Slimefun4/commit/73ad1d2c4ea861d9acab9f286c9da516404cf35c) (2022.6)
 - SoulJars Version: 最新构建 Build 7

**Comment by ybw0014** [comment]
配置文件中多写了个Evoker，已移除
